export const ControlData = [
  {
    id: 1,
    name_table: "01",
    titel: "ปลากระพงทอดน้ำปลา",
    image: "/images/123.jpg",
    priority: 1,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 2,
    name_table: "02",
    titel: "กะเพราหมูสับไข่เยี่ยวม้า",
    image: "/images/2.jpg",
    priority: 2,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 3,
    name_table: "03",
    titel: "ผัดพริกแกงหมูกรอบ",
    image: "/images/3.jpg",
    priority: 3,
    status: 3,
    food_menu: 3,
    order_number: "00000616",
  },
  {
    id: 4,
    name_table: "04",
    titel: "ฟัวกราส์ย่าง",
    image: "/images/4.jpg",
    priority: 4,
    status: 6,
    food_menu: 5,
    order_number: "00000616",
  },
  {
    id: 5,
    name_table: "05",
    titel: "เต้าหู้ไข่ & หมูสับผัด กระเทียมพริกไทย",
    image: "/images/11.jpg",
    priority: 5,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 6,
    name_table: "06",
    titel: "สปาเกตตีผัดขี้เมาทะเล",
    image: "/images/22.jpg",
    priority: 6,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 7,
    name_table: "07",
    titel: "ปลากระพงทอดน้ำปลา",
    image: "/images/33.jpg",
    priority: 7,
    status: 3,
    food_menu: 4,
    order_number: "00000616",
  },
  {
    id: 8,
    name_table: "08",
    titel: "ปลากระพงทอดน้ำปลา",
    image: "/images/44.jpg",
    priority: 8,
    status: 6,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 9,
    name_table: "09",
    titel: "ปลากระพงทอดน้ำปลา",
    image: "/images/55.jpg",
    priority: 9,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 10,
    name_table: "10",
    titel: "กะเพราหมูสับไข่เยี่ยวม้า",
    image: "/images/66.jpg",
    priority: 10,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 11,
    name_table: "11",
    titel: "ผัดพริกแกงหมูกรอบ",
    image: "/images/77.jpg",
    priority: 11,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 12,
    name_table: "12",
    titel: "เต้าหู้ไข่ & หมูสับผัด กระเทียมพริกไทย",
    image: "/images/123.jpg",
    priority: 12,
    status: 3,
    food_menu: 5,
    order_number: "00000616",
  },
  {
    id: 13,
    name_table: "13",
    titel: "สปาเกตตีผัดขี้เมาทะเล",
    image: "/images/1.jpg",
    priority: 13,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 14,
    name_table: "14",
    titel: "ปลากระพงทอดน้ำปลา",
    image: "/images/2.jpg",
    priority: 14,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 15,
    name_table: "15",
    titel: "ปลากระพงทอดน้ำปลา",
    image: "/images/3.jpg",
    priority: 15,
    status: 3,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 16,
    name_table: "16",
    titel: "ต้มยำกุ้ง",
    image: "/images/4.jpg",
    priority: 16,
    status: 3,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 17,
    name_table: "17",
    titel: "ฟัวกราส์ย่าง",
    image: "/images/11.jpg",
    priority: 17,
    status: 6,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 18,
    name_table: "18",
    titel: "ลาบหมู",
    image: "/images/22.jpg",
    priority: 18,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 19,
    name_table: "19",
    titel: "ข้าวไข่เจียวกุ้งสับ",
    image: "/images/33.jpg",
    priority: 19,
    status: 2,
    food_menu: 3,
    order_number: "00000616",
  },
  {
    id: 20,
    name_table: "20",
    titel: "แกงเขียวหวานไก่",
    image: "/images/44.jpg",
    priority: 20,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 21,
    name_table: "21",
    titel: "สเต็กเนื้อวากิว",
    image: "/images/55.jpg",
    priority: 21,
    status: 3,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 22,
    name_table: "22",
    titel: "หมูกรอบผัดพริกเกลือ",
    image: "/images/66.jpg",
    priority: 22,
    status: 6,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 23,
    name_table: "23",
    titel: "ข้าวหน้าเป็ด",
    image: "/images/77.jpg",
    priority: 23,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 24,
    name_table: "24",
    titel: "ข้าวหน้าไก่เทอริยากิ",
    image: "/images/123.jpg",
    priority: 24,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 25,
    name_table: "25",
    titel: "ซูชิแซลมอน",
    image: "/images/Gallery 1.jpg",
    priority: 25,
    status: 2,
    food_menu: 2,
    order_number: "00000616",
  },
  {
    id: 26,
    name_table: "26",
    titel: "สุกี้ทะเล",
    image: "/images/Gallery 2.jpg",
    priority: 26,
    status: 2,
    food_menu: 3,
    order_number: "00000616",
  },
  {
    id: 27,
    name_table: "27",
    titel: "หม้อไฟญี่ปุ่น",
    image: "/images/Gallery 3.jpg",
    priority: 27,
    status: 2,
    food_menu: 3,
    order_number: "00000616",
  },
  {
    id: 28,
    name_table: "28",
    titel: "ปลากะพงทอดน้ำปลา",
    image: "/images/Gallery 4.jpg",
    priority: 28,
    status: 2,
    food_menu: 3,
    order_number: "00000616",
  },
  {
    id: 29,
    name_table: "29",
    titel: "กุ้งเผา",
    image: "/images/Gallery 5.jpg",
    priority: 29,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
  {
    id: 30,
    name_table: "30",
    titel: "หอยนางรมทรงเครื่อง",
    image: "/images/Head-slide.jpg",
    priority: 30,
    status: 2,
    food_menu: 1,
    order_number: "00000616",
  },
];
