export const CustomTable = [
  {
    id: 1,
    name_table: "01",
    qrcode: "/images/001.jpg",
    priority: 1,
    status: 2,
  },
  {
    id: 2,
    name_table: "02",
    qrcode: "/images/002.jpg",
    priority: 2,
    status: 1,
  },
  {
    id: 3,
    name_table: "03",
    qrcode: "/images/003.jpg",
    priority: 3,
    status: 3,
  },
  {
    id: 4,
    name_table: "04",
    qrcode: "/images/004.jpg",
    priority: 4,
    status: 4,
  },
  {
    id: 5,
    name_table: "05",
    qrcode: "/images/005.jpg",
    priority: 5,
    status: 1,
  },
  {
    id: 6,
    name_table: "06",
    qrcode: "/images/006.jpg",
    priority: 3,
    status: 2,
  },
  {
    id: 7,
    name_table: "07",
    qrcode: "/images/007.jpg",
    priority: 2,
    status: 3,
  },
  {
    id: 8,
    name_table: "08",
    qrcode: "/images/008.jpg",
    priority: 1,
    status: 4,
  },
  {
    id: 9,
    name_table: "09",
    qrcode: "/images/009.jpg",
    priority: 4,
    status: 2,
  },
  {
    id: 10,
    name_table: "10",
    qrcode: "/images/010.jpg",
    priority: 5,
    status: 1,
  },
  {
    id: 11,
    name_table: "11",
    qrcode: "/images/011.jpg",
    priority: 1,
    status: 3,
  },
  {
    id: 12,
    name_table: "12",
    qrcode: "/images/012.jpg",
    priority: 2,
    status: 4,
  },
  {
    id: 13,
    name_table: "13",
    qrcode: "/images/013.jpg",
    priority: 3,
    status: 2,
  },
  {
    id: 14,
    name_table: "14",
    qrcode: "/images/014.jpg",
    priority: 4,
    status: 1,
  },
  {
    id: 15,
    name_table: "15",
    qrcode: "/images/015.jpg",
    priority: 5,
    status: 3,
  },
  {
    id: 16,
    name_table: "16",
    qrcode: "/images/016.jpg",
    priority: 1,
    status: 2,
  },
  {
    id: 17,
    name_table: "17",
    qrcode: "/images/017.jpg",
    priority: 2,
    status: 4,
  },
  {
    id: 18,
    name_table: "18",
    qrcode: "/images/018.jpg",
    priority: 3,
    status: 1,
  },
  {
    id: 19,
    name_table: "19",
    qrcode: "/images/019.jpg",
    priority: 4,
    status: 3,
  },
  {
    id: 20,
    name_table: "20",
    qrcode: "/images/020.jpg",
    priority: 5,
    status: 2,
  },
  {
    id: 21,
    name_table: "21",
    qrcode: "/images/021.jpg",
    priority: 1,
    status: 1,
  },
  {
    id: 22,
    name_table: "22",
    qrcode: "/images/022.jpg",
    priority: 2,
    status: 2,
  },
  {
    id: 23,
    name_table: "23",
    qrcode: "/images/023.jpg",
    priority: 3,
    status: 3,
  },
  {
    id: 24,
    name_table: "24",
    qrcode: "/images/024.jpg",
    priority: 4,
    status: 4,
  },
  {
    id: 25,
    name_table: "25",
    qrcode: "/images/025.jpg",
    priority: 5,
    status: 1,
  },
  {
    id: 26,
    name_table: "26",
    qrcode: "/images/026.jpg",
    priority: 1,
    status: 3,
  },
  {
    id: 27,
    name_table: "27",
    qrcode: "/images/027.jpg",
    priority: 2,
    status: 4,
  },
  {
    id: 28,
    name_table: "28",
    qrcode: "/images/028.jpg",
    priority: 3,
    status: 2,
  },
  {
    id: 29,
    name_table: "29",
    qrcode: "/images/029.jpg",
    priority: 4,
    status: 1,
  },
  {
    id: 30,
    name_table: "30",
    qrcode: "/images/030.jpg",
    priority: 5,
    status: 3,
  },
];
