export const FoodListData = [
  {
    id: 1,
    name: "ข้าวผัดกุ้ง",
    details: "ไม่ใส่หอม ไม่ใส่ผักชี ไม่เค็ม",
    quantity: 1,
    price: "120.00",
    oldPrice: "150.00",
  },
  {
    id: 2,
    name: "ก๋วยเตี๋ยวเรือ",
    details: "เผ็ดน้อย ไม่ใส่ถั่วงอก",
    quantity: 2,
    price: "45.00",
    oldPrice: "50.00",
  },
  {
    id: 3,
    name: "ต้มยำกุ้ง",
    details: "ไม่ใส่เห็ด ไม่เผ็ดมาก",
    quantity: 1,
    price: "200.00",
    oldPrice: "220.00",
  },
  {
    id: 4,
    name: "ส้มตำไทย",
    details: "ไม่ใส่ปลาร้า",
    quantity: 1,
    price: "60.00",
    oldPrice: "70.00",
  },
  {
    id: 5,
    name: "ไก่ทอด",
    details: "กรอบนอกนุ่มใน",
    quantity: 3,
    price: "90.00",
    oldPrice: "100.00",
  },
  {
    id: 6,
    name: "ข้าวมันไก่",
    details: "ไม่เอาหนัง",
    quantity: 1,
    price: "50.00",
    oldPrice: "60.00",
  },
  {
    id: 7,
    name: "ข้าวขาหมู",
    details: "เนื้อล้วน ไม่ใส่ไข่",
    quantity: 2,
    price: "80.00",
    oldPrice: "90.00",
  },
  {
    id: 8,
    name: "หมูกรอบ",
    details: "น้ำจิ้มสูตรพิเศษ",
    quantity: 1,
    price: "110.00",
    oldPrice: "120.00",
  },
  {
    id: 9,
    name: "ปลาทอด",
    details: "ไม่ใส่น้ำจิ้มหวาน",
    quantity: 1,
    price: "150.00",
    oldPrice: "170.00",
  },
  {
    id: 10,
    name: "ผัดไทยกุ้งสด",
    details: "ไม่ใส่ถั่ว",
    quantity: 1,
    price: "80.00",
    oldPrice: "90.00",
  },
  {
    id: 11,
    name: "ข้าวไข่เจียว",
    details: "ไข่เจียวฟู",
    quantity: 1,
    price: "40.00",
    oldPrice: "50.00",
  },
  {
    id: 12,
    name: "แกงเขียวหวานไก่",
    details: "เผ็ดปานกลาง",
    quantity: 1,
    price: "100.00",
    oldPrice: "120.00",
  },
];
