export const ViewTableData = [
  {
    id: 1,
    name_table: "1",
    qrcode: "/images/123.jpg",
    priority: 1,
    status: 1,
  },
  {
    id: 2,
    name_table: "2",
    qrcode: "/images/2.jpg",
    priority: 2,
    status: 2,
  },
  {
    id: 3,
    name_table: "3",
    qrcode: "/images/3.jpg",
    priority: 3,
    status: 3,
  },
  {
    id: 4,
    name_table: "4",
    qrcode: "/images/4.jpg",
    priority: 4,
    status: 4,
  },
  {
    id: 5,
    name_table: "5",
    qrcode: "/images/11.jpg",
    priority: 5,
    status: 2,
  },
  {
    id: 6,
    name_table: "6",
    qrcode: "/images/22.jpg",
    priority: 6,
    status: 2,
  },
  {
    id: 7,
    name_table: "7",
    qrcode: "/images/33.jpg",
    priority: 7,
    status: 3,
  },
  {
    id: 8,
    name_table: "8",
    qrcode: "/images/44.jpg",
    priority: 8,
    status: 4,
  },
  {
    id: 9,
    name_table: "9",
    qrcode: "/images/55.jpg",
    priority: 9,
    status: 1,
  },
  {
    id: 10,
    name_table: "10",
    qrcode: "/images/66.jpg",
    priority: 10,
    status: 2,
  },
  {
    id: 11,
    name_table: "11",
    qrcode: "/images/77.jpg",
    priority: 11,
    status: 1,
  },
  {
    id: 12,
    name_table: "12",
    qrcode: "/images/123.jpg",
    priority: 12,
    status: 3,
  },
  {
    id: 13,
    name_table: "13",
    qrcode: "/images/1.jpg",
    priority: 13,
    status: 1,
  },
  {
    id: 14,
    name_table: "14",
    qrcode: "/images/2.jpg",
    priority: 14,
    status: 1,
  },
  {
    id: 15,
    name_table: "15",
    qrcode: "/images/3.jpg",
    priority: 15,
    status: 3,
  },
  {
    id: 16,
    name_table: "16",
    qrcode: "/images/4.jpg",
    priority: 16,
    status: 3,
  },
  {
    id: 17,
    name_table: "17",
    qrcode: "/images/11.jpg",
    priority: 17,
    status: 4,
  },
  {
    id: 18,
    name_table: "18",
    qrcode: "/images/22.jpg",
    priority: 18,
    status: 1,
  },
  {
    id: 19,
    name_table: "19",
    qrcode: "/images/33.jpg",
    priority: 19,
    status: 1,
  },
  {
    id: 20,
    name_table: "20",
    qrcode: "/images/44.jpg",
    priority: 20,
    status: 1,
  },
  {
    id: 21,
    name_table: "21",
    qrcode: "/images/55.jpg",
    priority: 21,
    status: 3,
  },
  {
    id: 22,
    name_table: "22",
    qrcode: "/images/66.jpg",
    priority: 22,
    status: 4,
  },
  {
    id: 23,
    name_table: "23",
    qrcode: "/images/77.jpg",
    priority: 23,
    status: 1,
  },
  {
    id: 24,
    name_table: "24",
    qrcode: "/images/123.jpg",
    priority: 24,
    status: 1,
  },
  {
    id: 25,
    name_table: "25",
    qrcode: "/images/Gallery 1.jpg",
    priority: 25,
    status: 1,
  },
  {
    id: 26,
    name_table: "26",
    qrcode: "/images/Gallery 2.jpg",
    priority: 26,
    status: 1,
  },
  {
    id: 27,
    name_table: "27",
    qrcode: "/images/Gallery 3.jpg",
    priority: 27,
    status: 1,
  },
  {
    id: 28,
    name_table: "28",
    qrcode: "/images/Gallery 4.jpg",
    priority: 28,
    status: 1,
  },
  {
    id: 29,
    name_table: "29",
    qrcode: "/images/Gallery 5.jpg",
    priority: 29,
    status: 1,
  },
  {
    id: 30,
    name_table: "30",
    qrcode: "/images/Head-slide.jpg",
    priority: 30,
    status: 1,
  },
  {
    id: 31,
    name_table: "31",
    qrcode: "/images/Home 1.jpg",
    priority: 31,
    status: 4,
  },
  {
    id: 32,
    name_table: "32",
    qrcode: "/images/Home-2.jpg",
    priority: 32,
    status: 3,
  },
  {
    id: 33,
    name_table: "33",
    qrcode: "/images/Home-3.jpg",
    priority: 33,
    status: 1,
  },
  {
    id: 34,
    name_table: "34",
    qrcode: "/images/Home-4.jpg",
    priority: 34,
    status: 1,
  },
  {
    id: 35,
    name_table: "35",
    qrcode: "/images/jan.png",
    priority: 35,
    status: 1,
  },
  {
    id: 36,
    name_table: "36",
    qrcode: "/images/QR.jpg",
    priority: 36,
    status: 1,
  },
];
